### ISSUE TITLE
Error on saas sub-task on starting project

### ISSUE THREAD

**Issue by markved** [pnp/sp-dev-fx-webparts#497] opened 2018-05-02 01:41 UTC
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Expected or Desired Behavior
After "cd samples/react-list-form"  -->  "npm install" and "gulp serve" in terminal window, the build should be successful and serve workbench in the browser.

## Observed Behavior
After "cd samples/react-list-form"  -->  "npm install" and "gulp serve" in terminal window, the build fails with following error:
Error in plugin 'sass'
Message:
    src\common\_theming.module.scss
Error: File to import not found or unreadable: node_modules/office-ui-fabric-react/dist/sass/References.
       Parent style sheet: c:/SPFx/sp-dev-fx-webparts/samples/react-list-form/src/common/_theming.module.scss
        on line 1 of src/common/_theming.module.scss
>> @import '~office-ui-fabric-react/dist/sass/References';

## Steps to Reproduce

- Clone sp-dev-fx-webparts repo
- Open in VS code
- Change directory in terminal window to samples/react-list-form
- run command: npm install
- run command: gulp serve

## Submission Guidelines
I tried installing office-ui-fabric-react module but I don't seem to find references in dist sub-directory. npm install in the beginning should have installed any dependency.

**Comment by StfBauer** [comment] 2018-05-02 15:14
Have you checked you node_modules folder? In there you find an 'office-ui-fabric-react' folder.
I cannot reproduce your issue.

What you actually try to do is to make a clean install. Remove the node_modules folder and run npm install once again. Check if you get any warnings beside error.

What you actually can do to is to run:
```npm shrinkwrap```

before you install all node_modules once again.

**Comment by StfBauer** [comment] 2018-05-07 16:35
@markved Can you check the node and npm version you have installed.

For the node version simply execute the following command:
```node --version```

For the NPM
```npm --version```

Can you even please post the content of your ```package-lock.json```.

Thank you.

**Comment by markved** [comment] 2018-05-07 17:39
Node: v8.11.1
npm: 5.6.0

package-lock.json content too long to post here. I posted it below:
https://github.com/markved/temprepo/blob/master/package-lock.json

**Comment by samimansoor** [comment] 2018-05-07 19:47
I'm having a similar error with the same steps to reproduce. Node: v8.10.0, npm: 5.6.0

**Comment by TheTrickster1983** [comment] 2018-05-08 12:12
Same behavior here:  Node: v8.11.2 , npm: 5.6.0

**Comment by StfBauer** [comment] 2018-05-09 12:07
I cannot reproduce it for what so reason ever:
It works on Mac and Windows the exact same way.

**Node version:** v8.11.2
**NPM:** 5.6

Just as a quick checkup. These are the following packages installed globally:

```
+-- @microsoft/generator-sharepoint@1.4.0
+-- bower@1.8.0
+-- generator-simplestyle@0.3.0 -> C:\code\generator-simplestyle
+-- generator-webapp@3.0.1
+-- gulp@3.9.1
+-- npm@6.0.0
+-- npm-check-updates@2.14.2
+-- npm-windows-upgrade@4.1.0
+-- typescript@2.6.2
+-- typings@2.1.1
+-- yarn@1.3.2
+-- yo@2.0.0
```

This can be listed through the following command:

```
npm -g list --depth=0
```

@markved I also checked the package-lock.json and yours and mine are identical.

**Comment by markved** [comment] 2018-05-09 13:56
@StfBauer My local machine has following packages installed globally:

C:\Users\xxxxxx\AppData\Roaming\npm
+-- @microsoft/generator-sharepoint@1.4.1
+-- express-generator@4.16.0
+-- gulp@3.9.1
+-- truffle@4.1.3
+-- webpack@1.13.2
+-- windows-build-tools@2.3.0
`-- yo@2.0.2

I see a few additional ones installed on your machine but those don't seem like relevant ones.

**Comment by rishi41** [comment] 2018-05-14 14:38
Same problem on Node: v8.11.1 , npm: 5.6.0

**Comment by samimansoor** [comment] 2018-05-14 16:05
I can confirm that the issue is fixed with @rishi41 steps. Running npm shrinkwrap before install did the job for me - thank you @StfBauer

**Comment by mag210** [comment] 2018-07-03 11:14
@rishi41 this resolved the issue for me too. Should we run npm shinkwrap against SPFX webparts as a matter of course? Seems a good way to prevent newer packages from causing the webpart to fail on compile time?

**Comment by heinrich-ulbricht** [comment] 2018-11-15 08:53
I can also confirm that the issues goes away with @rishi41 steps. Node 10.13.0, npm 6.4.1 on Linux. This unfortunately (?) converts my package-lock.json to npm-shrinkwrap.json. Still not sure which one is better to have.

**Closed** 2020-05-20 00:26 UTC
