### ISSUE TITLE
 Identifier has already been declared

### ISSUE THREAD

**Issue by satoali17** [pnp/sp-dev-fx-webparts#2627] opened 2022-04-19 12:53 UTC
### Disclaimer

Yes

### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-script-editor

### Author(s)

@wobba

### Question

Hello all, 

we have written an script here which causes problems when switching pages. We guess that this is related to sharepoint online partial site loading.
Can you help here ? 

Here the example script: 
`<script>
    let queryString = window.location.search;
</script>`

Error message: 
`VM835:1 Uncaught SyntaxError: Identifier 'queryString' has already been declared
    at t.evalScript (script-editor-bundle_c9923e5cdc7d204b772ab3807c87e1fa.js:1)
    at t.<anonymous> (script-editor-bundle_c9923e5cdc7d204b772ab3807c87e1fa.js:1)
    at script-editor-bundle_c9923e5cdc7d204b772ab3807c87e1fa.js:1
    at Object.next (script-editor-bundle_c9923e5cdc7d204b772ab3807c87e1fa.js:1)
    at script-editor-bundle_c9923e5cdc7d204b772ab3807c87e1fa.js:1
    at new Promise (<anonymous>)
    at d (script-editor-bundle_c9923e5cdc7d204b772ab3807c87e1fa.js:1)
    at t.executeScript (script-editor-bundle_c9923e5cdc7d204b772ab3807c87e1fa.js:1)
    at t.render (script-editor-bundle_c9923e5cdc7d204b772ab3807c87e1fa.js:1)
    at t._renderWithAccessibleTitle (sp-pages-assembly_de-de_257cf847693da91363623a0070e8d4dd.js:71)`

Kind regards
Sait

**Comment by wobba** [comment] 2022-04-19 17:34
Not sure why this is and seems to only happen with `queryString`. Name it something different and error goes away. Also, you should use `var queryString` to be JavaScript compliant.. it's not TypeScript :) And I only see the error when I save the page. Not on refresh. If you're ok with using a different name on your variable I'll close this as seems debugging why it happens might take a while.

**Comment by kmosti** [comment] 2022-09-29 13:27
This is still an issue, and I have provided steps to reproduce (and a workaround) above.

**Comment by wobba** [comment] 2022-10-03 10:44
@kmosti do you propose the web part itself wrap user script in a self-executing function?

**Comment by kmosti** [comment] 2022-10-04 20:32
@wobba It's a bit of a tricky question because the web part shouldn't be overly opinionated as to which patterns developers use, but leaving this "as is" seems like a good way of deploying broken code.

So either wrap everything as you mentioned or perhaps better yet have some placeholder content where a simple html and script block is present and a self executing function is used, and maybe some comments explaining why caution should be used when using the global namespace?

**Comment by wobba** [comment] 2022-10-05 08:47
Something like this as an initial sample maybe, and also add it to the docs.

```javascript
<div>sample text<div>

// Option 1: Use self-executing function if code should run on each page load
<script>
    (function () {
        // put script here
    })() 
</script>

// Option 2: Script to be added on the page, living for the duration of a session
// E.g. google analytics
<script>
        // put script here
</script>
```

**Comment by kmosti** [comment] 2022-10-05 13:39
Exactly.

Maybe remove option 2, and modify the comment above the script tag to include a link to the documentation:

https://developer.mozilla.org/en-US/docs/Glossary/IIFE

**Comment by wobba** [comment] 2022-10-09 10:56
Added :)

**Closed by wobba** 2022-10-09 10:56 UTC
Labels: type:question, sample: react-script-editor
