### ISSUE TITLE
react-page-navigator HTML formatting bug

### ISSUE THREAD

**Issue by JaggB** [pnp/sp-dev-fx-webparts#1431] opened 2020-08-07 08:33 UTC
## Sample (which sample are you having trouble with)
react-page-navigator

## Authors
@aakashbhardwaj619 

## Expected or Desired Behavior
The text shouldn't have additional HTML codes such as < br > and < span >. This usually appears before or after the headers.

## Observed Behavior
The headers have additional formatting text, which changes when the page is publish. Each time the page is published, the text changes. Below are screenshots of the same webpart but the page has been published twice.

![image](https://user-images.githubusercontent.com/26111527/89625456-cd080800-d88f-11ea-8230-6a760aaffcd5.png)

![image](https://user-images.githubusercontent.com/26111527/89625471-d3967f80-d88f-11ea-80de-68e847fdf906.png)

As you can see, the < br > appears a number of times on the first image and only once in the second image

## Steps to Reproduce

1. Insert text on the page using the text webpart
2. Select text as Header 1, Header 2, etc.
3. Insert Page Navigator on right-hand vertical sections
3. Publish or Republish page.

# Environment Details (*Development & Target environment*)

- **OS**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v8.15.0
- **Browser(s)**: Chrome 84, FireFox 79
- **Tooling**: VS Code

**Comment by nanddeepn** [comment] 2020-08-12 08:42
Hi @hugoabernier 
Can I take this up?

**Comment by hugoabernier** [comment] 2020-08-12 13:35
Thanks @nanddeepn, the issue is now assigned to you.

**Comment by pchaotic** [comment] 2020-08-12 14:09
Hi @nanddeepn , I fixed this and a related issue with broken anchor tags in our tenant as described here: https://github.com/pnp/sp-dev-fx-webparts/issues/1037#issuecomment-672881064
So far, the fix works quite well. Just to let you know. :-)

**Comment by hugoabernier** [comment] 2020-08-12 14:55
@nanddeepn please make sure to mention both this issue and #1037 when you submit your PR so we can mark them both as resolved.

Thanks again for taking this one on!

**Comment by nanddeepn** [comment] 2020-08-12 14:57
> Hi @nanddeepn , I fixed this and a related issue with broken anchor tags in our tenant as described here: [#1037 (comment)](https://github.com/pnp/sp-dev-fx-webparts/issues/1037#issuecomment-672881064)
> So far, the fix works quite well. Just to let you know. :-)

Thanks @pchaotic and @hugoabernier

**Comment by nanddeepn** [comment] 2020-08-13 09:53
Hi @hugoabernier 
Submitted PR for this. Please review.

**Closed** 2020-08-16 02:22 UTC
Labels: help wanted, type:bug
