### ISSUE TITLE
I want to display the user column in react-list-form Web Parts.

### ISSUE THREAD

**Issue by tatenom** [pnp/sp-dev-fx-webparts#518] opened 2018-05-24 12:09 UTC
## Category

-  [x] Question
-  [ ] Bug
-  [ ] Enhancement

## Expected or Desired Behavior

I want to display the user column in react-list-form Web Parts. 
Do I have to add react-peoplepicker by myself in order to display the user column in react-list-form? 

## Observed Behavior

If I try to add a user column in a custom list with a react-list-form Web Parts, I can not add it. 

## Steps to Reproduce

・Add react list-form web parts 
・Select custom list with user column with property 
・The input form of the selected list is displayed, but the item of the user column is not displayed. Even if I try to add with plus button, it is not displayed.

**Comment by samimansoor** [comment] 2018-05-24 18:22
I'm encountering a similar issue. Is this working as intended because people picker is not a supported field?

**Comment by tatenom** [comment] 2018-05-24 22:29
I have not tried it yet. So I have to implement it myself.
Thank you very much.

**Comment by bubbleswap** [comment] 2019-03-01 22:17
Thank you for the web part! Successfully deployed it, though as stated by the above, cannot add "people picker" field nor "attachment" field. Is this by design or of limitations from what column type can be pulled into a web part?

**Comment by hugoabernier** [comment] 2020-05-20 00:35
@tatenom did you ever resolve this issue?

I'll go ahead and close it as there has been no activities here for a while. Feel free to open a new issue if you're still having troubles.

**Closed by hugoabernier** 2020-05-20 00:35 UTC
