### ISSUE TITLE
React-Carousel not renders png formatted images 

### ISSUE THREAD

**Issue by sivanu137** [pnp/sp-dev-fx-webparts#1636] opened 2020-12-10 07:36 UTC
## Expected or Desired Behavior
     The expected behavior is, whatever the image format in the picture library, the pictures should render in the carousel.

## Observed Behavior
      But the observed behavior is, only jpeg or jpg pictures are getting rendered in the carousel but now png format images.

##My Picture Library screenshot: 
![image](https://user-images.githubusercontent.com/31919925/101732898-f22db100-3ae3-11eb-8f5a-af696f35e04a.png)

I have 3 jpg format images and 2 png formatted images in this library, what happens is In carouse is, only shows jpg images but not png.

How we can get all jpeg || jpg || png images in carousel??
The service provider returns me an array length of 5 items from the picture library, but the carousel shows only 3 jpg formatted images only.

![image](https://user-images.githubusercontent.com/31919925/101735804-6ec28e80-3ae8-11eb-8c4e-2e4ced431025.png)

Thanks in advance !!!

**Comment by hugoabernier** [comment] 2020-12-10 07:41
Thanks for filing the issue @sivanu137, but I'm not the author of this sample. You may want to check again to make sure that the authors will get notified.

**Comment by sudharsank** [comment] 2020-12-10 09:41
@sivanu137 
I was able to replicate the issue. The issue is due to the uppercase on the file extension. When my file extension is **png** it is loaded and if it is **PNG** the file is not loaded. Try to check your file extension and make sure all lowercase. Meanwhile, I will update the solution and publish it.

@hugoabernier I will work on this issue.

**Comment by sudharsank** [comment] 2020-12-10 09:51
Hi @sivanu137 
The service call use **usingCaching** method to reduce the transaction calls to SharePoint Library. This will take some time to reflect with the new images uploaded to the library. I tried with jpg, jpeg and png images and all are displaying in the carousel.

**Comment by Abderahman88** [comment] 2020-12-11 00:10
PNG-files are supported.

![CarouselPng](https://user-images.githubusercontent.com/36161889/101844852-a6afed00-3b4d-11eb-8529-d8f43eec0839.png)

**Comment by hugoabernier** [comment] 2020-12-13 05:46
Hi @sivanu137 I hope that you were able to resolve this issue with @sudharsank and @Abderahman88 's help?

I'll go ahead and close this issue, If you need more help, please don't hesitate to open a new issue and we'll continue to dig deeper.

**Closed by hugoabernier** 2020-12-13 05:46 UTC
Labels: type:bug
