### ISSUE TITLE
react directory: Alpha index yield no results, search does

### ISSUE THREAD

**Issue by webbrewer** [pnp/sp-dev-fx-webparts#1133] opened 2020-02-06 18:49 UTC
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Authors
@hugoabernier 

## Expected or Desired Behavior

The alpha index above results will filter on initial of last name when clicked.

## Observed Behavior

Clicking any letter in the index gives "No users found in directory". Search does find people though.

## Steps to Reproduce

Build solution, upload to app catalog, add app to site, add web part to site page.

## Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by webbrewer** [comment] 2020-02-07 00:06
Additional issues: there seems to be a weird timing issue in the results returned. If I type "smith" sometimes I get just "smiths"; sometimes I get everyone whose name starts with "sm"; sometimes I get no results. Doesn't seem like the search queries are working as intended.

**Comment by hugoabernier** [comment] 2020-05-29 03:50
@webbrewer thanks for tagging me, but I'm not the author of this sample.

**Comment by petkir** [comment] 2020-07-17 20:08
Hi @hugoabernier you can assign this issue to me.

> Additional issues: there seems to be a weird timing issue in the results returned. If I type "smith" sometimes I get just "smiths"; sometimes I get everyone whose name starts with "sm"; sometimes I get no results. Doesn't seem like the search queries are working as intended.
And sometimes the results flash on the page and then disappear.

this looks like that sometimes a call is faster than the other, so the state will be updated with an outdated result. if you type fast a name it is every time a mixture what you have typed.

@webbrewer the original issue I'm not able to reproduce
by clicking on a letter a query/post ```_api/search/postquery``` will be executed with a query text
![image](https://user-images.githubusercontent.com/13123689/87825064-b82eea80-c876-11ea-8ea2-d00393a73e9d.png)

Please try in your browser the following URL
```https://xyz.sharepoint.com/_api/search/query?SourceId=%27b09a7990-05ea-4af9-81ef-edfab16c4e31%27&querytext=%27LastName:K*%27 ```
You have to change xyz to your tenant and this string search for all user with the Lastname K, if you have no user with K change it to any other letter.

Hopefully, you get a result count like this
![image](https://user-images.githubusercontent.com/13123689/87826467-38eee600-c879-11ea-9a14-4bd44c851eac.png)

**Closed** 2020-07-20 02:23 UTC
Labels: help wanted, type:bug
