### ISSUE TITLE
@react-page-navigator  - Functionality breaks when there is a special charcter in h1,h2,h3 tags.

### ISSUE THREAD

**Issue by mmohamedbasith** [pnp/sp-dev-fx-webparts#1037] opened 2019-10-18 15:49 UTC
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Authors

@aakashbhardwaj619 

## Expected or Desired Behavior

On click og link should works fine even if it has special characters

## Observed Behavior
Functionality breaks when there is a special charcter in h1,h2,h3 tags.

## Steps to Reproduce

1.Type 'How to start?' in heading1 font.
2.Save.
3.click the 'How to Start' in navigator webpart. 

Thanks for your contribution! Sharing is caring.

**Comment by aakashbhardwaj619** [comment] 2019-11-06 07:47
Hi Mohamed,

Thanks for reporting the issue.

I confirm that the issue is occurring for me as well when I try to add special characters in the heading. To fix the issue I would first need to analyze how the special characters are getting treated in the automatically created anchor tag. I would let you know once the fix is pushed to the updated version.

Regards,
Aakash

**Comment by mmohamedbasith** [comment] 2019-11-06 07:54
@aakashbhardwaj619  I did below to handle it . There are lot of special characters scenario & position of those charcters we need to test. If you find any effective way to handle it , please update.

headingValue = this.htmlDecode(headingValue);
var headingurl = headingValue.replace(/ /g, '-').replace(/^[^a-z]+|[^\w:!$*().-]+/gi, "-").replace(/-{2,}/g, '-');
 headingurl = headingurl.replace(/\-$/, '');

 public htmlDecode(input) {
        var e = document.createElement('div');
        e.innerHTML = input;
        return e.childNodes.length === 0 ? "" : e.childNodes[0].nodeValue;
    }

**Comment by hugoabernier** [comment] 2020-04-04 18:11
Thanks @mmohamedbasith. Can you confirm whether this is still an issue?

If so, I'd encourage you to submit a pull request with your fix.

Just let us know so we can mark the issue as closed or assign it to you.

If anyone else wants to help with this, just let us know and we'll assign it to you.

**Comment by mmohamedbasith** [comment] 2020-04-04 19:18
Yes issue still exist. I dont find this webpart and this solution as
reliable.Microsoft product team changes the pattern in which the special
charcters are handle in ID attribute of heading tags (i did workarounds to
make it work,but when the patterns changed ,i have to change the code
again). Due to changing nature of ID generation for special, this webpart
code cannot be reliable forever. I will not encourge users to use this
webpart in production environment.

(Note: there is one product level bug exists as well. When partial page
load happens, anchor tag does not load at all.)

**Comment by pchaotic** [comment] 2020-08-03 11:44
Any news on a planned fix on this issue?
Additionally, we found a related issue in the page navigator web part: If you style a heading (e.g. assign the color red, make it bold etc.) the page navigator web part will render this html tag.
![pagenavigatorbug](https://user-images.githubusercontent.com/68848347/89179148-6fbe3f00-d58f-11ea-88c6-49ef4000ada8.png)

**Comment by pchaotic** [comment] 2020-08-12 13:47
Ok, fixed it myself. This is what I did in SPServices.ts:
I changed the regex which is responsible for headingValue 
```
            let headingValue = HTMLString.substring(
              HTMLString.search(/<h[1-4]>/g) + 4,
              HTMLString.search(/<\/h[1-4]>/g)
            )
              .replace(/<.+?>/gi, "")
              .replace(/\&.+\;/gi, "");
```
and added two regex which are responsible for the anchorURL.
```
            let anchorUrl = `#${headingValue
              // Add special characters in RegEx below
              .replace(/\'|\?|\\|\/| |\&/g, "-")
              .replace(/--+/g, "-")}`.toLowerCase();
```

This should also fix the html rendering bug reported here: https://github.com/pnp/sp-dev-fx-webparts/issues/1431. Will do a pull request some time later.

### Detailed explanation of my approach:
**headingValue**
.replace(/<.+?>/gi, "") replaces in the headingValue any html tags like  <strong> </strong>
.replace(/\&.+\;/gi, "") replaces in the headingValue any &****; tags like &nbsp; 

**anchorURL**
.replace(/\'|\?|\\|\/| |\&/g, "-") replaces any blanks and special characters (list is for sure not complete) with "-"
.replace(/--+/g, "-") replaces any additional - with only one -; e.g. --- get replaced with -, -- get replaced with - etc.

**Comment by hugoabernier** [comment] 2020-08-25 02:13
@mmohamedbasith did you try the latest version submitted by @nanddeepn which resolves this issue?

I'll mark the issue as closed, but if you're still experiencing issues, please do not hesitate to open a new issue.

Thanks @nanddeepn for your help with this one.

**Closed by hugoabernier** 2020-08-25 02:13 UTC
Labels: Good First Issue 🏆, area:sample-code, help wanted, type:bug
