### ISSUE TITLE
React Content Query WebPart - Render image field

### ISSUE THREAD

**Issue by floriemoulin** [pnp/sp-dev-fx-webparts#1574] opened 2020-10-30 13:37 UTC
## Sample (which sample are you talking about)
(The fabulous) React Content Query WebPart 

## Authors

@PopWarner
@hugoabernier
@PaoloPia

## Question (the more details, the better)

I've just installed the content query web part on my SharePoint site and i am already a huge fan. 
There is one small issue that I haven't been able to resolve and wondered if you could help.

When I try to display a Picture field
![image](https://user-images.githubusercontent.com/11554528/97711183-0d58da00-1abd-11eb-9a9b-2180cf207c1c.png)

I get this kind of result 👎 
![image](https://user-images.githubusercontent.com/11554528/97711226-1c3f8c80-1abd-11eb-9589-611fb54fb3dd.png)

How can I do to display my wonderful pictures properly ?
Thank you for your help !

**Comment by Abderahman88** [comment] 2020-11-01 21:05
Images can be added with the following steps:

1) Go to 'Edit template content'
2) Add image-tag with the URL of the image
![picture_query](https://user-images.githubusercontent.com/36161889/97815376-ce2db300-1c8d-11eb-8d0f-515a979341cf.png)
3) Add some css for styling
![image_css](https://user-images.githubusercontent.com/36161889/97815420-1c42b680-1c8e-11eb-9007-b273db83015b.png)


**Result:**
![cat_lion](https://user-images.githubusercontent.com/36161889/97815428-2c5a9600-1c8e-11eb-8a09-e1acfc76576d.PNG)

**Comment by floriemoulin** [comment] 2020-11-02 10:11
Hi and thank you for your answer.
I try this morning (your answer and some other attempts) :
![image](https://user-images.githubusercontent.com/11554528/97852083-90b14000-1cf6-11eb-8a89-1ae067a836c9.png)
 and nothing seems to be working 👎 
![image](https://user-images.githubusercontent.com/11554528/97856061-11bf0600-1cfc-11eb-969a-404d37d75a65.png)

Did I miss something ?
Thank you again for your help

**Comment by Abderahman88** [comment] 2020-11-02 14:26
Is the "Icone" field of type "Image"?

![QueryList](https://user-images.githubusercontent.com/36161889/97878804-64f68000-1d1f-11eb-855b-02a5c17ea2eb.PNG)

**Comment by floriemoulin** [comment] 2020-11-02 14:52
My field is an **Image** field. 
I've just tried with an **Hyperlink/Picture field** and the format {{Pictogramme.rawValue.Url}} works fine.

![image](https://user-images.githubusercontent.com/11554528/97880953-11d1fc80-1d22-11eb-818c-926b73061448.png)

Is it possible to make it work with an image field ?

**Comment by Abderahman88** [comment] 2020-11-02 15:40
Hyperlink/Picture field is fine.

If you set to Picture.textValue, you normally get the URL of the image.

Can you test this?

![PictureTextvalue](https://user-images.githubusercontent.com/36161889/97887238-ece18780-1d29-11eb-9acf-f460db0bdcf2.PNG)

![PictureRawValue](https://user-images.githubusercontent.com/36161889/97887251-f1a63b80-1d29-11eb-84ad-459939a3a87f.png)

**Comment by floriemoulin** [comment] 2020-11-02 15:55
I confirm that the Hyperlink/Picture field type is working.
But I want to use the Image field type. 

With the Image field type, I try the following code : 
![image](https://user-images.githubusercontent.com/11554528/97889018-20bdac80-1d2c-11eb-9e80-84c7a3461994.png)

And I get this  :
![image](https://user-images.githubusercontent.com/11554528/97889081-34691300-1d2c-11eb-9453-258ef236c91a.png)

**Comment by hugoabernier** [comment] 2020-11-02 16:05
Try writing the following in your `img` tag instead?

```html
<img src="{{Pictogramme.textValue}}" />
```

**Comment by floriemoulin** [comment] 2020-11-02 16:11
With ![image](https://user-images.githubusercontent.com/11554528/97890808-48ae0f80-1d2e-11eb-961c-cfe4ac5ff705.png) : 

![image](https://user-images.githubusercontent.com/11554528/97890672-1a303480-1d2e-11eb-9f5a-bc4c6790bd15.png)

I can do a split but I am not sure if it's the best (the cleanest ?) way to display my picture.

**Comment by hugoabernier** [comment] 2020-11-02 16:26
Sorry, trying to do this over my phone and copied and pasted it wrong:

```html
<img src="{{Pictogramme.serverRelativeUrl}}" />
```

**Comment by Abderahman88** [comment] 2020-11-02 16:36
@hugoabernier I'm currently testing the scenario and I'm afraid this doesn't work.
Can't access directly the object property.

![image](https://user-images.githubusercontent.com/36161889/97892907-ed315100-1d30-11eb-8067-039db4707578.png)

**Comment by floriemoulin** [comment] 2020-11-02 16:36
No problem.

I try : 
![image](https://user-images.githubusercontent.com/11554528/97893551-b871c980-1d31-11eb-9664-7941a0158b42.png)

and, unfortunately, it's not better :(. Here is the generated HTML code : 
![image](https://user-images.githubusercontent.com/11554528/97893665-e1925a00-1d31-11eb-8a03-48f142a2f7e7.png)

**Comment by Abderahman88** [comment] 2020-11-02 16:38
@floriemoulin I know. This doesn't work. I will look further into this.

**Comment by Abderahman88** [comment] 2020-11-02 17:02
The issue is that the SharePoint REST API doesn't return an object, but a string (unlike Hyperlink/Picture)
That's why we can't access the object by the properties.

![ImageIssue](https://user-images.githubusercontent.com/36161889/97896075-e1478e00-1d34-11eb-84c4-934c07a6724c.png)

This needs to be fixed.

@hugoabernier Can you assign this to me?

**Comment by hugoabernier** [comment] 2020-11-02 18:25
@Abderahman88 I'm checking in an SPFx 1.11 upgraded version. Just testing it now. Do you mind validating my newer version with your fix -- and we can kill two birds with one stone?

**Comment by hugoabernier** [comment] 2020-11-02 18:36
I also added a new normalized field called `jsonValue` that will allow you to parse a JSON field. That way, we can use

```html
<img src={{Image.jsonValue.serverRelativeUrl}}"/>
```

It should make it more "future proof" with new types of field and give us more flexibility.

**Comment by Abderahman88** [comment] 2020-11-02 19:09
@hugoabernier The new normalized field 'jsonValue' is a great idea.

I was replacing the rawValue with the JSON-object.

`rawValue: this.jsonParseField(result[viewField] || result[viewField + 'Id'])`

```
private jsonParseField(value: any): any{
        if (typeof value === 'string') {
            try {
                let jsonObject = JSON.parse(value);
                return jsonObject;
            }
            catch {
               return value;
            }
        }
        return value;
    }
```

It does work 😄 
![fixImage](https://user-images.githubusercontent.com/36161889/97908575-2eccf680-1d47-11eb-849c-1e207e5527ae.PNG)

![FixImage2](https://user-images.githubusercontent.com/36161889/97908644-41dfc680-1d47-11eb-950c-8c04b5f313b2.PNG)

**Comment by hugoabernier** [comment] 2020-11-02 19:20
@Abderahman88 great minds think alike :-)

I chose to use a new normalized field to make sure that I wasn't breaking older templates that may already use the values.

I'll combine my changes with your `jsonParseField` and will create a pull request. If you're ok with validating the changes, I'm more than happy to give you the credit for the fix (all I did, really was upgrading the sample).

I'll flag you when I submit the PR.

**Closed** 2020-11-02 22:32 UTC
Labels: type:question

**Comment by hugoabernier** [comment] 2020-11-03 17:33
@floriemoulin I have uploaded the latest `.sppkg` file which solves the problem.

You can find it at https://github.com/pnp/sp-dev-fx-webparts/raw/master/samples/react-content-query-webpart/Online/sharepoint/solution/react-content-query-webpart.sppkg

In your template, you can use:

```html
<img src={{Image.jsonValue.serverRelativeUrl}}"/>
```

You may want to set a max `height` or `width` to make sure that the image doesn't take over the entire page.

Thanks for your patience, and thanks @Abderahman88 for collaborating with me on solving this issue.

**Comment by floriemoulin** [comment] 2020-11-17 14:38
Thanks a lot @hugoabernier and @Abderahman88 for your help and for this quick solving.
It's perfect !!!
