### ISSUE TITLE
js-modern-calendar: Error 404 on Install

### ISSUE THREAD

**Issue by firozozman** [pnp/sp-dev-fx-webparts#1685] opened 2021-01-25 20:53 UTC
Which sample are you having trouble with? js-modern-calendar

## Authors
Jeremy Coleman (MCP, PC Professional, Inc.)
Nanddeep Nachan (@NanddeepNachan)

## Expected or Desired Behavior

What should it do?

User must be able to download from git-hub, build and deploy the application.

## Observed Behavior

What does it do?
I was able to download the source code. When I ran the npm install, it threw the following error:

404 Not Found - GET https://registry.npmjs.org/event-stream/-/event-stream-3.3.6.tgz
'event-stream@3.3.6' is not in the npm registry.
You should bug the author to publish it.

## Steps to Reproduce

1. Download the source code from git
2. in node.js command line utility, navigate to webpart folder in the sample directory
3. run npm install

# Environment Details (*Development & Target environment*)

- **OS**: Windows Server 2016
- **Target Environment**:  SharePoint Server 2019 
- **Framework**: Node.js v6.14.11
- **Browser(s)**: Chrome and IE
- **Tooling**:  VS Code

**Comment by jcoleman-pcprofessional** [comment] 2021-01-25 21:34
> event-stream-3.3.6.tgz

This sample needs to be updated.  In the meantime you can resolve this by allowing npm to install a new version of event stream:

Delete your node_modules folder
Delete the package-lock.json file in the project root
Run npm install

**Comment by firozozman** [comment] 2021-01-28 15:41
Thanks @jcoleman-pcprofessional 

I was able to build by making those adjustments. Now I get Failed to load component, manifest not found error when I add this Web Part to a page.

Anything else needs update?

**Comment by Ravikadri** [comment] 2021-02-09 23:25
@fabiofranzini, 

Tested after upgrading to the latest version and seems like the issue is fixed now. 
![image](https://user-images.githubusercontent.com/9435596/107441878-e6ae3480-6aea-11eb-9b91-fd14d5e74dc1.png)

@hugoabernier ,

I have the pull request for the same https://github.com/pnp/sp-dev-fx-webparts/pull/1702

**Closed** 2021-02-11 06:14 UTC
Labels: type:bug

**Comment by firozozman** [comment] 2021-02-15 03:11
Thanks, @Ravikadri, and @hugoabernier
