### ISSUE TITLE
Unable to build solution

### ISSUE THREAD

**Issue by sudeepghatak** [pnp/sp-dev-fx-webparts#1919] opened 2021-06-02 05:39 UTC
### Sample

react-list-form

### Author(s)

@DanyWyss

### What happened?

Error - [tsc] src/webparts/listForm/components/formFields/SPFieldRichTextEdit.tsx(23,13): error TS2339: Property 'init' does not exist on type 'typeof import("C:/Users/sudeep.ghatak/Downloads/sp-dev-fx-webparts-master/samples/react-list-form/node_modules/tinymce/tinymce")'.
(26,17): error TS2339: Property 'editors' does not exist on type 'typeof import("C:/Users/sudeep.ghatak/Downloads/sp-dev-fx-webparts-master/samples/react-list-form/node_modules/tinymce/tinymce")'.
Error - [tsc] src/webparts/listForm/components/formFields/SPFieldRichTextEdit.tsx(27,17): error TS2339: Property 'editors' does not exist on type 'typeof import("C:/Users/sudeep.ghatak/Downloads/sp-dev-fx-webparts-master/samples/react-list-form/node_modules/tinymce/tinymce")'.
Error - 'tsc' sub task errored after 9.46 s 
 exited with code 2

### Steps to reproduce

1. npm install
2. gulp build

### Expected behavior

Solution should build without errors

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### SPFx version

1.9.1

### Node.js version

v10.15.1

**Comment by Abderahman88** [comment] 2021-06-08 20:48
The latest version of react-list-form uses spfx 1.10

I tested it and have no problems.

![image](https://user-images.githubusercontent.com/36161889/121254888-14459780-c8ab-11eb-8245-b1aa180664ad.png)

I would recommend getting the most recent version, delete` node_modules` and run `npm install` again.

**Comment by hugoabernier** [comment] 2021-06-21 15:37
Closing this issue as unable to reproduce. If you're still running into this issue, please don't hesitate to open a new issue and provide the actual error messages that you're getting so that we can help you further.

**Closed** 2021-06-21 15:36 UTC
Labels: type:bug-suspected
