### ISSUE TITLE
React-Calendar background and text color

### ISSUE THREAD

**Issue by joshuaOwen** [pnp/sp-dev-fx-webparts#1004] opened 2019-09-24 00:18 UTC
- [ ] Question
- [x] Bug
- [ ] Enhancement

 Please excuse me I'm very new to programing and I'm not completely sure if this issue would be considered a bug or an enhancement.

@joaojmendes

With the react-calendar web-part the background is set to white, and the text conforms to the theme of the site. My companies theme is a darker grey color, with white text. Since the text turns white on a white background I end up with no text in the web-part. I just need some help with fixing the issue, I'd like to make the background and borderlines conform to my site theme. I'm just not advanced enough to do it yet. If anyone has any ideas on how to fix it, without changing the theme of the site I would really appreciate it!!!!

Link to the sample:
https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-calendar

**Comment by hugoabernier** [comment] 2020-04-04 19:36
Hey @joshuaOwen  did you ever get this issue resolved?

If you haven't see his blog post, Stefan Bauer (the master!) has a [great article on the topic](https://n8d.at/how-to-use-theme-colors-in-spfx-web-parts/).

If you solve the issue, remember that we accept community contributions in this repo (wink, wink, nudge, nudge).

**Comment by hugoabernier** [comment] 2020-05-31 19:09
Closing this issue as there appears to be a new version of the web part. Please let us know if the issue isn't resolved.

**Closed by hugoabernier** 2020-05-31 19:09 UTC
Labels: Good First Issue 🏆, area:sample-code, help wanted, status:fixed, type:enhancement
