### ISSUE TITLE
react-m365-services-health - 403 Forbidden when calling MS Graph

### ISSUE THREAD

**Issue by maartendevos** [pnp/sp-dev-fx-webparts#3793] opened 2023-07-10 13:00 UTC
### Disclaimer

Yes

### Sample

react-m365-services-health

### Contributor(s)

@HarminderSethi

### What happened?

Receiving a 403 (Forbidden) when calling MS Graph, https://graph.microsoft.com/v1.0/admin/serviceAnnouncement/healthOverviews?$expand=issues.
<img width="312" alt="image" src="https://github.com/pnp/sp-dev-fx-webparts/assets/4604200/e47910c1-a345-4823-beb3-0525b701a0ea">

Approved this in SharePoint admin center (API Access)
<img width="451" alt="image" src="https://github.com/pnp/sp-dev-fx-webparts/assets/4604200/9b9a5d55-8b6f-49d5-a321-e1c0a5c6cc49">

### Steps to reproduce

1. npm i 
2. gulp serve
3.  or build an deploy solution
4. check result in webvpart and check console of your browser for more information
<img width="265" alt="image" src="https://github.com/pnp/sp-dev-fx-webparts/assets/4604200/fb19f627-725a-4f28-bc88-65ac13d03407">

### Expected behavior

Show list of services with status:
<img width="308" alt="image" src="https://github.com/pnp/sp-dev-fx-webparts/assets/4604200/abd874a5-1b77-498b-a7b6-8b022b178eeb">

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [ ] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

16.3.2

### What version of Node.js is required by the sample?

v16 | v14 | v12

### Paste the results of SPFx doctor

√ SharePoint Framework v1.16.1
√ Node v16.13.2
√ yo v4.3.1
√ gulp-cli v2.3.0
√ bundled typescript used

**Comment by HarminderSethi** [comment] 2023-07-10 14:21
@maartendevos this solution requires 'ServiceHealth.Read.All' permissions. so post installation of webpart, you need to get the permission approved from SharePoint admin center. Please let me know if the access is approved and you are still getting the error. if not, please follow the steps provided in [https://learn.microsoft.com/en-us/sharepoint/api-access](https://learn.microsoft.com/en-us/sharepoint/api-access)

**Comment by maartendevos** [comment] 2023-07-10 14:32
The thing is it's nicely approved
<img width="889" alt="image" src="https://github.com/pnp/sp-dev-fx-webparts/assets/4604200/e1515d8f-dc10-46ae-b095-dff92ff7f759">

**Comment by maartendevos** [comment] 2023-07-10 14:33
And yes also visible in: SharePoint Online Client Extensibility Web Application Principal

**Comment by HarminderSethi** [comment] 2023-07-10 14:53
I have observed that it take some time in applying the permissions.

**Comment by maartendevos** [comment] 2023-07-10 15:06
I cleared cache, I used in-private browsing and deployed and approved it 7 hours ago:
<img width="682" alt="image" src="https://github.com/pnp/sp-dev-fx-webparts/assets/4604200/5718d240-7037-4f2a-ab72-5d48d33526f7">
Strange... Will check tomorrow again and hopefully can close this issue ;-)

**Comment by HarminderSethi** [comment] 2023-07-10 15:16
Also please try in non incognito/private mode

**Comment by maartendevos** [comment] 2023-07-11 06:55
I still have the same issue, checked it in guest mode and in Chrome, Firefox

**Comment by HarminderSethi** [comment] 2023-07-11 07:09
Yes I am also facing the issue. I checked this solution last Friday only and it was working fine. I am finding the root cause. seems to be something related to token

**Comment by maartendevos** [comment] 2023-07-11 07:13
The token seems not valid for the ServiceHealth.Read.All, for other graph endpoints like groups it seems fine, don't really understand it. Settings seems fine.

**Comment by carlingregory** [comment] 2023-07-11 07:26
Hello, I have the same issue/behavior. With my test, i suspect also the token because i have made a test with Graph Explorer, it's ok. And i use the good permission as in Graph Explorer but it in my SPFX web part, it doesn't work.

**Comment by carlingregory** [comment] 2023-10-16 06:30
@HarminderSethi, Hello, we don't have any news about this issue. It still exists. What can we do to fix it ?

**Comment by carlingregory** [comment] 2023-10-17 06:08
Hi @HarminderSethi, @maartendevos, @v-saikirang, i also tried the solution in the link but it still didn't work

**Comment by HarminderSethi** [comment] 2023-10-19 04:32
@CG081 I have raised a service ticket with Microsoft for this issue. will share the updates..

**Comment by glarroze** [comment] 2023-12-07 15:37
Hi all, is there any news about the ticket ? I have the same 403 issue on this end point.

**Comment by HarminderSethi** [comment] 2023-12-07 15:48
> Hi all, is there any news about the ticket ? I have the same 403 issue on this end point. 

Last week I had a call with Microsoft graph support team where I showed the issue. I have shared all the required logs. Yesterday I have sent the follow up email and still waiting for response.

**Comment by maartendevos** [comment] 2024-01-05 15:17
This issue is still open

**Comment by HarminderSethi** [comment] 2024-01-06 07:05
@maartendevos Microsoft is still looking into this issue. will update on this thread once I receive any response from Microsoft.

**Comment by HarminderSethi** [comment] 2024-02-02 09:42
@maartendevos @glarroze  @CG081 @v-saikirang  From past few weeks I am following up with Microsoft support team and not getting any response. The best I can do is to call the graph api using azure function. The only drawaback of this approach will be hosting the azure function and register Azure Entra ID App.

**Comment by HarminderSethi** [comment] 2024-02-07 05:11
@maartendevos @glarroze @CG081 @v-saikirang This is the latest response I have received. Can anyone of you share your tenant Id as requested by MS support team?

![image](https://github.com/pnp/sp-dev-fx-webparts/assets/17841313/c20276c7-b409-4c4c-840b-eb0e5781a94e)

**Comment by HarminderSethi** [comment] 2024-02-10 18:19
@maartendevos @glarroze @CG081 @v-saikirang  I have created the pull request https://github.com/pnp/sp-dev-fx-webparts/pull/4697 that will replace the graph api with azure function. As this issue is not not sample specific and is related to Graph API and SPFx communication so  this issue can be closed as pull request is created for alternate solution. 

The sample can also be downloaded from https://github.com/HarminderSethi/SPFx-Samples/blob/main/react-M365-Service-Health/README.md

**Comment by HarminderSethi** [comment] 2024-02-10 18:27
@hugoabernier I did not find option to close the issue so need your help in closing this issue as I have submitted PR with alternate solution for problem being faced.

**Closed** 2024-02-10 18:50 UTC
Labels: type:bug-suspected, sample: react-m365-services-health
