### ISSUE TITLE
React Pnpjsexplorer

### ISSUE THREAD

**Issue by mikezimm** [pnp/sp-dev-fx-webparts#1558] opened 2020-10-20 14:20 UTC
## Sample (which sample are you having trouble with)
React Pnpjsexplorer

## Authors
@siddharth-vaghasia @kunj-sangani 

## Expected or Desired Behavior
The page command bar icons would all be in the correct place

## Observed Behavior
The command bar buttons load in correct place at first.
Then when the webpart renders (it's a half second behind), the page Edit/Publish button is way off the page to the right.
![image](https://user-images.githubusercontent.com/49648086/96599347-d1a06200-12bd-11eb-96e2-4674c5bee1ac.png)

## Steps to Reproduce
I packaged and deployed to an app catalog and put the webpart on a page

# Environment Details (*Development & Target environment*)
Chrome & Internet Explorer, SharePoint Online

**Comment by Abderahman88** [comment] 2020-10-20 17:27
Is this an issue caused by the webpart? Looks to me like a SharePoint-bug.

**Comment by siddharth-vaghasia** [comment] 2020-10-20 19:01
@mikezimm  - thanks for reporting this...looks like an issue.... We will check and get back to you...

**Comment by siddharth-vaghasia** [comment] 2020-10-20 19:02
@hugoabernier  - you can assign this to me..

**Comment by mikezimm** [comment] 2020-10-21 05:03
It only happens when I put this WebPart on a page.  None others that I can tell.   And it was prett consistent.

Thanks

**Comment by Abderahman88** [comment] 2020-10-28 00:28
@mikezimm @siddharth-vaghasia I made a fix for this problem.

**Closed** 2020-10-31 02:47 UTC
Labels: type:bug

**Comment by siddharth-vaghasia** [comment] 2020-10-31 05:25
@Abderahman88  - thanks....!!
