### ISSUE TITLE
React-Calendar All Day Event issue

### ISSUE THREAD

**Issue by jacobchris6** [pnp/sp-dev-fx-webparts#2132] opened 2021-11-11 22:07 UTC
### Sample

https://github.com/pnp/sp-dev-fx-webparts/blob/main/samples/react-calendar

### Author(s)

@mohammadamer

### What happened?

When I create a new event and toggle the "All Day Event", the event is created but spans two days. With start time at 07:00H on first day and goes until 06:59 the next day.  

I noticed a previous issue with similar results in case that helps zero in on it.
[https://github.com/pnp/sp-dev-fx-webparts/pull/2102](url)

### Steps to reproduce

1. Create new event for a particular date, toggle "All Day Event". Save
![image](https://user-images.githubusercontent.com/84941029/141374160-bfe995f3-7e7c-4f84-a37b-b0975a36a856.png)

2.  Event spans two days (It did initially show on one. I refreshed the page and then it was over two)
![image](https://user-images.githubusercontent.com/84941029/141374280-31cf9761-8a62-4810-9419-991bda08d772.png)

3. Hover over the event to see the hours. 
![image](https://user-images.githubusercontent.com/84941029/141374347-f6d0c40c-0442-4877-aa09-b2c9c37d5ed5.png)

### Expected behavior

Not go into the next day.

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [ ] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Node.js version

v10.24.1

### Additional environment details

Using this in GCC High (government) tenant SharePoint Online. I also see the issue on our commercial tenant SPO when tested over there for kicks.

**Comment by mohammadamer** [comment] 2021-11-12 07:35
Thanks @jacobchris6 for reporting the issue. I'll try to reproduce it in my machine and look into it.
@hugoabernier Could you please assign it me.

**Comment by mikezimm** [comment] 2021-11-12 23:09
@jacobchris6 , @hugoabernier ,

Because of the 7 hour offset, it sounds to me like something to do with the timezone.

I know when I was working on a project with times, it was really complex.

You have UTC Time, you have the Site's time zone and you have an [individual user's time zone](https://sharepointmaven.com/sharepoint-time-zone/).

I know that SharePoint saves the time in UTC but the webpart either needs to convert it to UTC or also provide the time with the timezone for it to be saved correctly.

Hope that helps :)

**Comment by mikezimm** [comment] 2021-11-12 23:24
@hugoabernier :
Suggestion:  At least have an option (default = true) to show the user what timezone things are showing in.
To make it fancy, then add a time zone picker the end user can select to re-draw the calendar in any time zone they want.

**Comment by mikezimm** [comment] 2021-11-15 22:47
@jacobchris6 , @hugoabernier ,
Was this closed by accident?  I'm just curious since it sounded like it was going to be looked at.

Thanks

**Comment by mohammadamer** [comment] 2021-11-22 00:38
@jacobchris6 
simply this  function parseDate in this file parseRecurrentEvent.ts is causing this issue.
This function is parsing the date wrongly and that's why you see it like that and this is happening in the second load.


You can replace this function

```
  public parseDate(date: any, allDay: any) {
    if (typeof date == 'string') {
      if (allDay) {
        if (date.lastIndexOf('Z') == date.length - 1) {
          const dt = date.substring(0, date.length - 1);
          return new Date(dt);
        }
      }
      else {
        return new Date(date);
      }
    }
    return date;
  }
```

with to avoid the wrong parsing of dates

```
  public parseDate(date: any, allDay: any) {
    if (typeof date == 'string') {
      return new Date(date);
    }
    return date;
  }
```

**Comment by jacobchris6** [comment] 2021-11-22 17:19
@mohammadamer. That worked!  Thank you for for looking into it so quickly.

**Comment by hugoabernier** [comment] 2021-11-22 19:13
Thank you @mohammadamer. I have tagged this as **good first issue** and **help wanted**, in case someone from the community wants to make a permanent fix

**Comment by mohammadamer** [comment] 2021-11-22 19:24
@hugoabernier PR #2148  to fix this issue has been submitted.

**Closed** 2021-12-02 07:10 UTC
Labels: type:bug-suspected, sample: react-calendar
