### ISSUE TITLE
react-graph-telephonedirectory: When i place the SPFx WebPart on a modern Page i get the error login.microsoftonline.com refused to connect

### ISSUE THREAD

**Issue by schneika** [pnp/sp-dev-fx-webparts#1390] opened 2020-07-15 13:46 UTC
## Sample ##
react-graph-telephonedirectory

## Authors
Dipen Shah (@Dips_365)
@dips365 

## Question (the more details, the better)
When i place the SPFx WebPart on a modern Page i get the error:  
login.microsoftonline.com refused to connect

I have already SharePoint Microsoft Graph API Access Consent and build and bundle sppkg Package with --ship

## Question
Something missing from my side?

**Comment by dips365** [comment] 2020-07-15 19:22
@schneika I replicated same issue on my tenant.
I removed the access from the API management.Same error came to my tenant after remove the access.
I grant access by global admin and check webpart. It seems as expected.
Can you please check that access approved by global admin user?

**Comment by dips365** [comment] 2020-07-17 09:15
@hugoabernier Can you assign to me?

**Comment by PopWarner** [comment] 2020-07-24 01:10
Thank @dips365! This has been assigned to you. Please keep us updated on status. Thank you so much for your help! 💜🧡

**Comment by dips365** [comment] 2020-07-27 06:51
@schneika Can you please check access granted through global admin from API management ?

**Comment by ChristerRussberg** [comment] 2020-07-29 18:48
Hi
I have the same problem ie getting the error "login.microsoftonline.com refused to connect".

**Comment by dips365** [comment] 2020-08-07 04:00
@ChristerRussberg 
I replicated same issue on my tenant.
I removed the access from the API management.Same error came to my tenant after remove the access.
I grant access by global admin and check web-part. It seems as expected.
Can you please check that access approved by global admin user?

**Comment by schneika** [comment] 2020-08-11 07:48
Yes i definetely have granted Global Admin Consent to the Graph API in SharePoint Admin Center.
Sometime it works. But mostly not. Seems to have something to do with cross origin authentication or single sign on?

This is the Edge Chromium Debug Inspect: 

Warning!
Use of this tool exposes you to potential security threats which can result in others gaining access to your personal Office 365 data (documents, emails, conversations and more). Make sure you trust the person or organization that asked you to access this tool before proceeding.
Learn more here: https://technet.microsoft.com/en-us/library/bb794823.aspx
24A preload for '<URL>' is found, but is not used because the request credentials mode does not match. Consider taking a look at crossorigin attribute.
VM1589:34 A preload for 'https://publiccdn.sharepointonline.com/ipiapps.sharepoint.com/sites/appcatalog/ClientSideAssets/e1a26cc8-a086-454f-9f16-9aeb0a276bcc/react-graph-telephonedirectory-telephonedirectorywebpartstrings_en-us_8ffb17ee64616b093f1a46f55430d7c5.js' is found, but is not used because the request credentials mode does not match. Consider taking a look at crossorigin attribute.
e.load @ VM1589:34
load @ VM1589:29
load @ VM1589:18
fetch @ VM1589:18
check @ VM1589:20
enable @ VM1589:23
enable @ VM1589:28
eval @ VM1589:23
eval @ VM1589:8
v @ VM1589:7
enable @ VM1589:22
init @ VM1589:17
eval @ VM1589:27
setTimeout (async)
e.nextTick @ VM1589:32
g @ VM1589:26
requirejs @ VM1589:32
(anonymous) @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
e._requirePromise @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
e.requireLoad @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
e.load @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
g @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
m @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
(anonymous) @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
(anonymous) @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
e @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
_ @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
t._loadComponentWithExecutor @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
e.loadComponent @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
t.loadComponent @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
e.loadComponentById @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
e.loadComponentById @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
t._preloadComponents @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
t.onBeforePageLoad @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
t.onLoad @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
t.onLoad @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
t._load @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
e._initializeApplication @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
e._initializeApplicationWithTelemetry @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
e.startApplication @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
e.navigate @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
e.navigateToApplication @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
e._navigateToApplication @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
e._executePlatformCode @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
e._startApplication @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
e.startApplication @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
e._startApplication @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
e._startApplication @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
(anonymous) @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
Promise.then (async)
e.start @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
loaderStart @ Contosoportal:122
startSpfx @ Contosoportal:134
(anonymous) @ Contosoportal:161
(anonymous) @ Contosoportal:165
Show 18 more frames from Library code
VM1589:34 A preload for 'https://publiccdn.sharepointonline.com/ipiapps.sharepoint.com/sites/appcatalog/ClientSideAssets/e1a26cc8-a086-454f-9f16-9aeb0a276bcc/react-graph-telephonedirectory-controlstrings_en-us_52a6ba12e17213cb432213e7a90b16e0.js' is found, but is not used because the request credentials mode does not match. Consider taking a look at crossorigin attribute.
e.load @ VM1589:34
load @ VM1589:29
load @ VM1589:18
fetch @ VM1589:18
check @ VM1589:20
enable @ VM1589:23
enable @ VM1589:28
eval @ VM1589:23
eval @ VM1589:8
v @ VM1589:7
enable @ VM1589:22
init @ VM1589:17
eval @ VM1589:27
setTimeout (async)
e.nextTick @ VM1589:32
g @ VM1589:26
requirejs @ VM1589:32
(anonymous) @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
e._requirePromise @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
e.requireLoad @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
e.load @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
g @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
m @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
(anonymous) @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
(anonymous) @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
e @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
_ @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
t._loadComponentWithExecutor @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
e.loadComponent @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
t.loadComponent @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
e.loadComponentById @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
e.loadComponentById @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
t._preloadComponents @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
t.onBeforePageLoad @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
t.onLoad @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
t.onLoad @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
t._load @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
e._initializeApplication @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
e._initializeApplicationWithTelemetry @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
e.startApplication @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
e.navigate @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
e.navigateToApplication @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
e._navigateToApplication @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
e._executePlatformCode @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
e._startApplication @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
e.startApplication @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
e._startApplication @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
e._startApplication @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
(anonymous) @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
Promise.then (async)
e.start @ sp-pages-assembly_en-us_b3f3efdb98b60faeb8b52e064fedba42.js:1
loaderStart @ Contosoportal:122
startSpfx @ Contosoportal:134
(anonymous) @ Contosoportal:161
(anonymous) @ Contosoportal:165
Show 18 more frames from Library code

**Comment by dips365** [comment] 2020-08-11 08:36
@schneika Thanks for reporting this.
I will reproduce same to my end and update the code with solution.

**Comment by Abderahman88** [comment] 2020-10-27 23:44
Is this still an open issue?

I tested the webpart and it works. (tested in Chrome and MS Edge)

**Comment by mortenfa** [comment] 2020-11-24 07:45
Same problem here. The problem seems to be with Azure auth/current token. If I install/deploy the app as global admin and the user is authenticated the error is there. After user logout from AAD and revisiting the page/wp it works after login. It seems that the page cannot open an authentication pop-up or register SSO

**Closed** 2020-12-16 06:00 UTC
Labels: status:answered, type:question

**Comment by pmeripe** [comment] 2021-06-30 01:28
Suddenly I am also having the same with the web parts which deployed in 2018. Any help would be really appreciated.

Thanks!
